 CREATE VIEW JFAS.SPLAN_CAT_MASTER_LIST_VIEW (NTH_POS, SPLAN_CAT_ID, SPLAN_CAT_PARENT_ID, PATH, FULL_PATH)
  AS SELECT LEVEL AS NTH_POS, 
                  SPLAN_CAT_ID, 
                  SPLAN_CAT_PARENT_ID,  
                  SUBSTR(SYS_CONNECT_BY_PATH(ml.SPLAN_CAT_ID, ','), 2)||',' AS PATH
                  ,SPLAN_PKG.f_getFullHieratchyPath(SPLAN_CAT_ID) AS FULL_PATH
  FROM SPLAN_CAT_MASTER_LIST ml
 WHERE ml.SPLAN_SECTION_CODE != 'SUM'
  START WITH SPLAN_CAT_PARENT_ID = 0           
  CONNECT BY NOCYCLE PRIOR SPLAN_CAT_ID = SPLAN_CAT_PARENT_ID
  ;
 