  CREATE SEQUENCE  "JFAS"."SEQ_SPLAN_TRANS"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1330 CACHE 20 NOORDER  NOCYCLE ;

--------------------------------------------------------
--  File created - Monday-April-13-2015   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table SPLAN_TRANS
--------------------------------------------------------

  CREATE TABLE "JFAS"."SPLAN_TRANS" 
   (	"SPLAN_TRANS_ID" NUMBER, 
	"TRANS_DATE" DATE DEFAULT SYSDATE, 
	"TRANS_DESC" VARCHAR2(1000), 
	"PY" NUMBER, 
	"TRANS_NOTE" VARCHAR2(1000), 
	"TRANS_STATUS_CODE" VARCHAR2(10) DEFAULT 'O', 
	"TRANS_TYPE_CODE" VARCHAR2(10) DEFAULT 'INIT', 
	"CREATE_USER" VARCHAR2(20) DEFAULT 'mstein', 
	"CREATE_DATE" DATE DEFAULT SYSDATE, 
	"UPDATE_USER" VARCHAR2(20) DEFAULT 'mstein', 
	"UPDATE_DATE" DATE DEFAULT SYSDATE
   ) ;

   COMMENT ON COLUMN "JFAS"."SPLAN_TRANS"."TRANS_STATUS_CODE" IS 'See tbl LU_CODE';
   COMMENT ON COLUMN "JFAS"."SPLAN_TRANS"."TRANS_TYPE_CODE" IS 'See tbl LU_CODE';
--REM INSERTING into JFAS.SPLAN_TRANS
--SET DEFINE OFF;

Insert into JFAS.SPLAN_TRANS (SPLAN_TRANS_ID,TRANS_DATE,TRANS_DESC,PY,TRANS_NOTE,TRANS_STATUS_CODE,TRANS_TYPE_CODE,CREATE_USER,CREATE_DATE,UPDATE_USER,UPDATE_DATE) values (1279,to_date('13-APR-15','DD-MON-RR'),'Initial spend plan amount',2014,null,'O','INIT','sas',to_date('13-APR-15','DD-MON-RR'),'sas',to_date('13-APR-15','DD-MON-RR'));
Insert into JFAS.SPLAN_TRANS (SPLAN_TRANS_ID,TRANS_DATE,TRANS_DESC,PY,TRANS_NOTE,TRANS_STATUS_CODE,TRANS_TYPE_CODE,CREATE_USER,CREATE_DATE,UPDATE_USER,UPDATE_DATE) values (1280,to_date('13-APR-15','DD-MON-RR'),'Initial spend plan amount',2014,null,'O','INIT','sas',to_date('13-APR-15','DD-MON-RR'),'sas',to_date('13-APR-15','DD-MON-RR'));
Insert into JFAS.SPLAN_TRANS (SPLAN_TRANS_ID,TRANS_DATE,TRANS_DESC,PY,TRANS_NOTE,TRANS_STATUS_CODE,TRANS_TYPE_CODE,CREATE_USER,CREATE_DATE,UPDATE_USER,UPDATE_DATE) values (1281,to_date('13-APR-15','DD-MON-RR'),'Initial spend plan amount',2014,null,'O','INIT','sas',to_date('13-APR-15','DD-MON-RR'),'sas',to_date('13-APR-15','DD-MON-RR'));
Insert into JFAS.SPLAN_TRANS (SPLAN_TRANS_ID,TRANS_DATE,TRANS_DESC,PY,TRANS_NOTE,TRANS_STATUS_CODE,TRANS_TYPE_CODE,CREATE_USER,CREATE_DATE,UPDATE_USER,UPDATE_DATE) values (1282,to_date('13-APR-15','DD-MON-RR'),'Initial spend plan amount',2014,null,'O','INIT','sas',to_date('13-APR-15','DD-MON-RR'),'sas',to_date('13-APR-15','DD-MON-RR'));
Insert into JFAS.SPLAN_TRANS (SPLAN_TRANS_ID,TRANS_DATE,TRANS_DESC,PY,TRANS_NOTE,TRANS_STATUS_CODE,TRANS_TYPE_CODE,CREATE_USER,CREATE_DATE,UPDATE_USER,UPDATE_DATE) values (1283,to_date('13-APR-15','DD-MON-RR'),'Initial spend plan amount',2014,null,'O','INIT','sas',to_date('13-APR-15','DD-MON-RR'),'sas',to_date('13-APR-15','DD-MON-RR'));
Insert into JFAS.SPLAN_TRANS (SPLAN_TRANS_ID,TRANS_DATE,TRANS_DESC,PY,TRANS_NOTE,TRANS_STATUS_CODE,TRANS_TYPE_CODE,CREATE_USER,CREATE_DATE,UPDATE_USER,UPDATE_DATE) values (1284,to_date('13-APR-15','DD-MON-RR'),'Initial spend plan amount',2014,null,'O','INIT','sas',to_date('13-APR-15','DD-MON-RR'),'sas',to_date('13-APR-15','DD-MON-RR'));
Insert into JFAS.SPLAN_TRANS (SPLAN_TRANS_ID,TRANS_DATE,TRANS_DESC,PY,TRANS_NOTE,TRANS_STATUS_CODE,TRANS_TYPE_CODE,CREATE_USER,CREATE_DATE,UPDATE_USER,UPDATE_DATE) values (1285,to_date('13-APR-15','DD-MON-RR'),'Initial spend plan amount',2014,null,'O','INIT','sas',to_date('13-APR-15','DD-MON-RR'),'sas',to_date('13-APR-15','DD-MON-RR'));
Insert into JFAS.SPLAN_TRANS (SPLAN_TRANS_ID,TRANS_DATE,TRANS_DESC,PY,TRANS_NOTE,TRANS_STATUS_CODE,TRANS_TYPE_CODE,CREATE_USER,CREATE_DATE,UPDATE_USER,UPDATE_DATE) values (1286,to_date('13-APR-15','DD-MON-RR'),'Initial spend plan amount',2014,null,'O','INIT','sas',to_date('13-APR-15','DD-MON-RR'),'sas',to_date('13-APR-15','DD-MON-RR'));
Insert into JFAS.SPLAN_TRANS (SPLAN_TRANS_ID,TRANS_DATE,TRANS_DESC,PY,TRANS_NOTE,TRANS_STATUS_CODE,TRANS_TYPE_CODE,CREATE_USER,CREATE_DATE,UPDATE_USER,UPDATE_DATE) values (1287,to_date('13-APR-15','DD-MON-RR'),'Initial spend plan amount',2014,null,'O','INIT','sas',to_date('13-APR-15','DD-MON-RR'),'sas',to_date('13-APR-15','DD-MON-RR'));
Insert into JFAS.SPLAN_TRANS (SPLAN_TRANS_ID,TRANS_DATE,TRANS_DESC,PY,TRANS_NOTE,TRANS_STATUS_CODE,TRANS_TYPE_CODE,CREATE_USER,CREATE_DATE,UPDATE_USER,UPDATE_DATE) values (1288,to_date('13-APR-15','DD-MON-RR'),'Initial spend plan amount',2014,null,'O','INIT','sas',to_date('13-APR-15','DD-MON-RR'),'sas',to_date('13-APR-15','DD-MON-RR'));
Insert into JFAS.SPLAN_TRANS (SPLAN_TRANS_ID,TRANS_DATE,TRANS_DESC,PY,TRANS_NOTE,TRANS_STATUS_CODE,TRANS_TYPE_CODE,CREATE_USER,CREATE_DATE,UPDATE_USER,UPDATE_DATE) values (1289,to_date('13-APR-15','DD-MON-RR'),'Initial spend plan amount',2014,null,'O','INIT','sas',to_date('13-APR-15','DD-MON-RR'),'sas',to_date('13-APR-15','DD-MON-RR'));
Insert into JFAS.SPLAN_TRANS (SPLAN_TRANS_ID,TRANS_DATE,TRANS_DESC,PY,TRANS_NOTE,TRANS_STATUS_CODE,TRANS_TYPE_CODE,CREATE_USER,CREATE_DATE,UPDATE_USER,UPDATE_DATE) values (1290,to_date('13-APR-15','DD-MON-RR'),'Initial spend plan amount',2014,null,'O','INIT','sas',to_date('13-APR-15','DD-MON-RR'),'sas',to_date('13-APR-15','DD-MON-RR'));
Insert into JFAS.SPLAN_TRANS (SPLAN_TRANS_ID,TRANS_DATE,TRANS_DESC,PY,TRANS_NOTE,TRANS_STATUS_CODE,TRANS_TYPE_CODE,CREATE_USER,CREATE_DATE,UPDATE_USER,UPDATE_DATE) values (1291,to_date('13-APR-15','DD-MON-RR'),'Initial spend plan amount',2014,null,'O','INIT','sas',to_date('13-APR-15','DD-MON-RR'),'sas',to_date('13-APR-15','DD-MON-RR'));
Insert into JFAS.SPLAN_TRANS (SPLAN_TRANS_ID,TRANS_DATE,TRANS_DESC,PY,TRANS_NOTE,TRANS_STATUS_CODE,TRANS_TYPE_CODE,CREATE_USER,CREATE_DATE,UPDATE_USER,UPDATE_DATE) values (1292,to_date('13-APR-15','DD-MON-RR'),'Initial spend plan amount',2014,null,'O','INIT','sas',to_date('13-APR-15','DD-MON-RR'),'sas',to_date('13-APR-15','DD-MON-RR'));
Insert into JFAS.SPLAN_TRANS (SPLAN_TRANS_ID,TRANS_DATE,TRANS_DESC,PY,TRANS_NOTE,TRANS_STATUS_CODE,TRANS_TYPE_CODE,CREATE_USER,CREATE_DATE,UPDATE_USER,UPDATE_DATE) values (1293,to_date('13-APR-15','DD-MON-RR'),'Initial spend plan amount',2014,null,'O','INIT','sas',to_date('13-APR-15','DD-MON-RR'),'sas',to_date('13-APR-15','DD-MON-RR'));
Insert into JFAS.SPLAN_TRANS (SPLAN_TRANS_ID,TRANS_DATE,TRANS_DESC,PY,TRANS_NOTE,TRANS_STATUS_CODE,TRANS_TYPE_CODE,CREATE_USER,CREATE_DATE,UPDATE_USER,UPDATE_DATE) values (1294,to_date('13-APR-15','DD-MON-RR'),'Initial spend plan amount',2014,null,'O','INIT','sas',to_date('13-APR-15','DD-MON-RR'),'sas',to_date('13-APR-15','DD-MON-RR'));
Insert into JFAS.SPLAN_TRANS (SPLAN_TRANS_ID,TRANS_DATE,TRANS_DESC,PY,TRANS_NOTE,TRANS_STATUS_CODE,TRANS_TYPE_CODE,CREATE_USER,CREATE_DATE,UPDATE_USER,UPDATE_DATE) values (1295,to_date('13-APR-15','DD-MON-RR'),'Initial spend plan amount',2014,null,'O','INIT','sas',to_date('13-APR-15','DD-MON-RR'),'sas',to_date('13-APR-15','DD-MON-RR'));
Insert into JFAS.SPLAN_TRANS (SPLAN_TRANS_ID,TRANS_DATE,TRANS_DESC,PY,TRANS_NOTE,TRANS_STATUS_CODE,TRANS_TYPE_CODE,CREATE_USER,CREATE_DATE,UPDATE_USER,UPDATE_DATE) values (1296,to_date('13-APR-15','DD-MON-RR'),'Initial spend plan amount',2014,null,'O','INIT','sas',to_date('13-APR-15','DD-MON-RR'),'sas',to_date('13-APR-15','DD-MON-RR'));
Insert into JFAS.SPLAN_TRANS (SPLAN_TRANS_ID,TRANS_DATE,TRANS_DESC,PY,TRANS_NOTE,TRANS_STATUS_CODE,TRANS_TYPE_CODE,CREATE_USER,CREATE_DATE,UPDATE_USER,UPDATE_DATE) values (1297,to_date('13-APR-15','DD-MON-RR'),'Initial spend plan amount',2014,null,'O','INIT','sas',to_date('13-APR-15','DD-MON-RR'),'sas',to_date('13-APR-15','DD-MON-RR'));
Insert into JFAS.SPLAN_TRANS (SPLAN_TRANS_ID,TRANS_DATE,TRANS_DESC,PY,TRANS_NOTE,TRANS_STATUS_CODE,TRANS_TYPE_CODE,CREATE_USER,CREATE_DATE,UPDATE_USER,UPDATE_DATE) values (1298,to_date('13-APR-15','DD-MON-RR'),'Initial spend plan amount',2014,null,'O','INIT','sas',to_date('13-APR-15','DD-MON-RR'),'sas',to_date('13-APR-15','DD-MON-RR'));
Insert into JFAS.SPLAN_TRANS (SPLAN_TRANS_ID,TRANS_DATE,TRANS_DESC,PY,TRANS_NOTE,TRANS_STATUS_CODE,TRANS_TYPE_CODE,CREATE_USER,CREATE_DATE,UPDATE_USER,UPDATE_DATE) values (1299,to_date('13-APR-15','DD-MON-RR'),'Initial spend plan amount',2014,null,'O','INIT','sas',to_date('13-APR-15','DD-MON-RR'),'sas',to_date('13-APR-15','DD-MON-RR'));
Insert into JFAS.SPLAN_TRANS (SPLAN_TRANS_ID,TRANS_DATE,TRANS_DESC,PY,TRANS_NOTE,TRANS_STATUS_CODE,TRANS_TYPE_CODE,CREATE_USER,CREATE_DATE,UPDATE_USER,UPDATE_DATE) values (1300,to_date('13-APR-15','DD-MON-RR'),'Initial spend plan amount',2014,null,'O','INIT','sas',to_date('13-APR-15','DD-MON-RR'),'sas',to_date('13-APR-15','DD-MON-RR'));
Insert into JFAS.SPLAN_TRANS (SPLAN_TRANS_ID,TRANS_DATE,TRANS_DESC,PY,TRANS_NOTE,TRANS_STATUS_CODE,TRANS_TYPE_CODE,CREATE_USER,CREATE_DATE,UPDATE_USER,UPDATE_DATE) values (1301,to_date('13-APR-15','DD-MON-RR'),'Initial spend plan amount',2014,null,'O','INIT','sas',to_date('13-APR-15','DD-MON-RR'),'sas',to_date('13-APR-15','DD-MON-RR'));
Insert into JFAS.SPLAN_TRANS (SPLAN_TRANS_ID,TRANS_DATE,TRANS_DESC,PY,TRANS_NOTE,TRANS_STATUS_CODE,TRANS_TYPE_CODE,CREATE_USER,CREATE_DATE,UPDATE_USER,UPDATE_DATE) values (1302,to_date('13-APR-15','DD-MON-RR'),'Initial spend plan amount',2014,null,'O','INIT','sas',to_date('13-APR-15','DD-MON-RR'),'sas',to_date('13-APR-15','DD-MON-RR'));
Insert into JFAS.SPLAN_TRANS (SPLAN_TRANS_ID,TRANS_DATE,TRANS_DESC,PY,TRANS_NOTE,TRANS_STATUS_CODE,TRANS_TYPE_CODE,CREATE_USER,CREATE_DATE,UPDATE_USER,UPDATE_DATE) values (1303,to_date('13-APR-15','DD-MON-RR'),'Initial spend plan amount',2014,null,'O','INIT','sas',to_date('13-APR-15','DD-MON-RR'),'sas',to_date('13-APR-15','DD-MON-RR'));
Insert into JFAS.SPLAN_TRANS (SPLAN_TRANS_ID,TRANS_DATE,TRANS_DESC,PY,TRANS_NOTE,TRANS_STATUS_CODE,TRANS_TYPE_CODE,CREATE_USER,CREATE_DATE,UPDATE_USER,UPDATE_DATE) values (1304,to_date('13-APR-15','DD-MON-RR'),'Initial spend plan amount',2014,null,'O','INIT','sas',to_date('13-APR-15','DD-MON-RR'),'sas',to_date('13-APR-15','DD-MON-RR'));
Insert into JFAS.SPLAN_TRANS (SPLAN_TRANS_ID,TRANS_DATE,TRANS_DESC,PY,TRANS_NOTE,TRANS_STATUS_CODE,TRANS_TYPE_CODE,CREATE_USER,CREATE_DATE,UPDATE_USER,UPDATE_DATE) values (1305,to_date('13-APR-15','DD-MON-RR'),'Initial spend plan amount',2014,null,'O','INIT','sas',to_date('13-APR-15','DD-MON-RR'),'sas',to_date('13-APR-15','DD-MON-RR'));
Insert into JFAS.SPLAN_TRANS (SPLAN_TRANS_ID,TRANS_DATE,TRANS_DESC,PY,TRANS_NOTE,TRANS_STATUS_CODE,TRANS_TYPE_CODE,CREATE_USER,CREATE_DATE,UPDATE_USER,UPDATE_DATE) values (1306,to_date('13-APR-15','DD-MON-RR'),'Initial spend plan amount',2014,null,'O','INIT','sas',to_date('13-APR-15','DD-MON-RR'),'sas',to_date('13-APR-15','DD-MON-RR'));
Insert into JFAS.SPLAN_TRANS (SPLAN_TRANS_ID,TRANS_DATE,TRANS_DESC,PY,TRANS_NOTE,TRANS_STATUS_CODE,TRANS_TYPE_CODE,CREATE_USER,CREATE_DATE,UPDATE_USER,UPDATE_DATE) values (1307,to_date('13-APR-15','DD-MON-RR'),'Initial spend plan amount',2014,null,'O','INIT','sas',to_date('13-APR-15','DD-MON-RR'),'sas',to_date('13-APR-15','DD-MON-RR'));
Insert into JFAS.SPLAN_TRANS (SPLAN_TRANS_ID,TRANS_DATE,TRANS_DESC,PY,TRANS_NOTE,TRANS_STATUS_CODE,TRANS_TYPE_CODE,CREATE_USER,CREATE_DATE,UPDATE_USER,UPDATE_DATE) values (1308,to_date('13-APR-15','DD-MON-RR'),'Initial spend plan amount',2014,null,'O','INIT','sas',to_date('13-APR-15','DD-MON-RR'),'sas',to_date('13-APR-15','DD-MON-RR'));
Insert into JFAS.SPLAN_TRANS (SPLAN_TRANS_ID,TRANS_DATE,TRANS_DESC,PY,TRANS_NOTE,TRANS_STATUS_CODE,TRANS_TYPE_CODE,CREATE_USER,CREATE_DATE,UPDATE_USER,UPDATE_DATE) values (1309,to_date('13-APR-15','DD-MON-RR'),'Initial spend plan amount',2014,null,'O','INIT','sas',to_date('13-APR-15','DD-MON-RR'),'sas',to_date('13-APR-15','DD-MON-RR'));
Insert into JFAS.SPLAN_TRANS (SPLAN_TRANS_ID,TRANS_DATE,TRANS_DESC,PY,TRANS_NOTE,TRANS_STATUS_CODE,TRANS_TYPE_CODE,CREATE_USER,CREATE_DATE,UPDATE_USER,UPDATE_DATE) values (1310,to_date('13-APR-15','DD-MON-RR'),'Initial spend plan amount',2014,null,'O','INIT','sas',to_date('13-APR-15','DD-MON-RR'),'sas',to_date('13-APR-15','DD-MON-RR'));
Insert into JFAS.SPLAN_TRANS (SPLAN_TRANS_ID,TRANS_DATE,TRANS_DESC,PY,TRANS_NOTE,TRANS_STATUS_CODE,TRANS_TYPE_CODE,CREATE_USER,CREATE_DATE,UPDATE_USER,UPDATE_DATE) values (1311,to_date('13-APR-15','DD-MON-RR'),'Initial spend plan amount',2014,'test','O','INIT','sas',to_date('13-APR-15','DD-MON-RR'),'sas',to_date('13-APR-15','DD-MON-RR'));
Insert into JFAS.SPLAN_TRANS (SPLAN_TRANS_ID,TRANS_DATE,TRANS_DESC,PY,TRANS_NOTE,TRANS_STATUS_CODE,TRANS_TYPE_CODE,CREATE_USER,CREATE_DATE,UPDATE_USER,UPDATE_DATE) values (1312,to_date('13-APR-15','DD-MON-RR'),'Initial spend plan amount',2014,null,'O','INIT','sas',to_date('13-APR-15','DD-MON-RR'),'sas',to_date('13-APR-15','DD-MON-RR'));
Insert into JFAS.SPLAN_TRANS (SPLAN_TRANS_ID,TRANS_DATE,TRANS_DESC,PY,TRANS_NOTE,TRANS_STATUS_CODE,TRANS_TYPE_CODE,CREATE_USER,CREATE_DATE,UPDATE_USER,UPDATE_DATE) values (1313,to_date('13-APR-15','DD-MON-RR'),'Initial spend plan amount',2014,null,'O','INIT','sas',to_date('13-APR-15','DD-MON-RR'),'sas',to_date('13-APR-15','DD-MON-RR'));
Insert into JFAS.SPLAN_TRANS (SPLAN_TRANS_ID,TRANS_DATE,TRANS_DESC,PY,TRANS_NOTE,TRANS_STATUS_CODE,TRANS_TYPE_CODE,CREATE_USER,CREATE_DATE,UPDATE_USER,UPDATE_DATE) values (1314,to_date('13-APR-15','DD-MON-RR'),'Initial spend plan amount',2014,null,'O','INIT','sas',to_date('13-APR-15','DD-MON-RR'),'sas',to_date('13-APR-15','DD-MON-RR'));
Insert into JFAS.SPLAN_TRANS (SPLAN_TRANS_ID,TRANS_DATE,TRANS_DESC,PY,TRANS_NOTE,TRANS_STATUS_CODE,TRANS_TYPE_CODE,CREATE_USER,CREATE_DATE,UPDATE_USER,UPDATE_DATE) values (1315,to_date('13-APR-15','DD-MON-RR'),'Initial spend plan amount',2014,null,'O','INIT','sas',to_date('13-APR-15','DD-MON-RR'),'sas',to_date('13-APR-15','DD-MON-RR'));
Insert into JFAS.SPLAN_TRANS (SPLAN_TRANS_ID,TRANS_DATE,TRANS_DESC,PY,TRANS_NOTE,TRANS_STATUS_CODE,TRANS_TYPE_CODE,CREATE_USER,CREATE_DATE,UPDATE_USER,UPDATE_DATE) values (1316,to_date('13-APR-15','DD-MON-RR'),'Initial spend plan amount',2014,null,'O','INIT','sas',to_date('13-APR-15','DD-MON-RR'),'sas',to_date('13-APR-15','DD-MON-RR'));
Insert into JFAS.SPLAN_TRANS (SPLAN_TRANS_ID,TRANS_DATE,TRANS_DESC,PY,TRANS_NOTE,TRANS_STATUS_CODE,TRANS_TYPE_CODE,CREATE_USER,CREATE_DATE,UPDATE_USER,UPDATE_DATE) values (1317,to_date('13-APR-15','DD-MON-RR'),'Initial spend plan amount',2014,null,'O','INIT','sas',to_date('13-APR-15','DD-MON-RR'),'sas',to_date('13-APR-15','DD-MON-RR'));
Insert into JFAS.SPLAN_TRANS (SPLAN_TRANS_ID,TRANS_DATE,TRANS_DESC,PY,TRANS_NOTE,TRANS_STATUS_CODE,TRANS_TYPE_CODE,CREATE_USER,CREATE_DATE,UPDATE_USER,UPDATE_DATE) values (1318,to_date('13-APR-15','DD-MON-RR'),'Initial spend plan amount',2014,null,'O','INIT','sas',to_date('13-APR-15','DD-MON-RR'),'sas',to_date('13-APR-15','DD-MON-RR'));
Insert into JFAS.SPLAN_TRANS (SPLAN_TRANS_ID,TRANS_DATE,TRANS_DESC,PY,TRANS_NOTE,TRANS_STATUS_CODE,TRANS_TYPE_CODE,CREATE_USER,CREATE_DATE,UPDATE_USER,UPDATE_DATE) values (1319,to_date('13-APR-15','DD-MON-RR'),'Initial spend plan amount',2014,null,'O','INIT','sas',to_date('13-APR-15','DD-MON-RR'),'sas',to_date('13-APR-15','DD-MON-RR'));
Insert into JFAS.SPLAN_TRANS (SPLAN_TRANS_ID,TRANS_DATE,TRANS_DESC,PY,TRANS_NOTE,TRANS_STATUS_CODE,TRANS_TYPE_CODE,CREATE_USER,CREATE_DATE,UPDATE_USER,UPDATE_DATE) values (1320,to_date('13-APR-15','DD-MON-RR'),'Initial spend plan amount',2014,null,'O','INIT','sas',to_date('13-APR-15','DD-MON-RR'),'sas',to_date('13-APR-15','DD-MON-RR'));
Insert into JFAS.SPLAN_TRANS (SPLAN_TRANS_ID,TRANS_DATE,TRANS_DESC,PY,TRANS_NOTE,TRANS_STATUS_CODE,TRANS_TYPE_CODE,CREATE_USER,CREATE_DATE,UPDATE_USER,UPDATE_DATE) values (1321,to_date('13-APR-15','DD-MON-RR'),'Initial spend plan amount',2014,null,'O','INIT','sas',to_date('13-APR-15','DD-MON-RR'),'sas',to_date('13-APR-15','DD-MON-RR'));
Insert into JFAS.SPLAN_TRANS (SPLAN_TRANS_ID,TRANS_DATE,TRANS_DESC,PY,TRANS_NOTE,TRANS_STATUS_CODE,TRANS_TYPE_CODE,CREATE_USER,CREATE_DATE,UPDATE_USER,UPDATE_DATE) values (1322,to_date('13-APR-15','DD-MON-RR'),'Initial spend plan amount',2014,null,'O','INIT','sas',to_date('13-APR-15','DD-MON-RR'),'sas',to_date('13-APR-15','DD-MON-RR'));
Insert into JFAS.SPLAN_TRANS (SPLAN_TRANS_ID,TRANS_DATE,TRANS_DESC,PY,TRANS_NOTE,TRANS_STATUS_CODE,TRANS_TYPE_CODE,CREATE_USER,CREATE_DATE,UPDATE_USER,UPDATE_DATE) values (1323,to_date('13-APR-15','DD-MON-RR'),'Initial spend plan amount',2014,null,'O','INIT','sas',to_date('13-APR-15','DD-MON-RR'),'sas',to_date('13-APR-15','DD-MON-RR'));
Insert into JFAS.SPLAN_TRANS (SPLAN_TRANS_ID,TRANS_DATE,TRANS_DESC,PY,TRANS_NOTE,TRANS_STATUS_CODE,TRANS_TYPE_CODE,CREATE_USER,CREATE_DATE,UPDATE_USER,UPDATE_DATE) values (1324,to_date('13-APR-15','DD-MON-RR'),'Initial spend plan amount',2014,null,'O','INIT','sas',to_date('13-APR-15','DD-MON-RR'),'sas',to_date('13-APR-15','DD-MON-RR'));

--------------------------------------------------------
--  DDL for Index SPLAN_TRANS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "JFAS"."SPLAN_TRANS_PK" ON "JFAS"."SPLAN_TRANS" ("SPLAN_TRANS_ID") 
  ;
--------------------------------------------------------
--  Constraints for Table SPLAN_TRANS
--------------------------------------------------------

  ALTER TABLE "JFAS"."SPLAN_TRANS" MODIFY ("UPDATE_DATE" NOT NULL ENABLE);
  ALTER TABLE "JFAS"."SPLAN_TRANS" MODIFY ("UPDATE_USER" NOT NULL ENABLE);
  ALTER TABLE "JFAS"."SPLAN_TRANS" MODIFY ("CREATE_DATE" NOT NULL ENABLE);
  ALTER TABLE "JFAS"."SPLAN_TRANS" MODIFY ("CREATE_USER" NOT NULL ENABLE);
  ALTER TABLE "JFAS"."SPLAN_TRANS" MODIFY ("TRANS_TYPE_CODE" NOT NULL ENABLE);
  ALTER TABLE "JFAS"."SPLAN_TRANS" MODIFY ("TRANS_STATUS_CODE" NOT NULL ENABLE);
  ALTER TABLE "JFAS"."SPLAN_TRANS" MODIFY ("PY" NOT NULL ENABLE);
  ALTER TABLE "JFAS"."SPLAN_TRANS" MODIFY ("TRANS_DATE" NOT NULL ENABLE);
  ALTER TABLE "JFAS"."SPLAN_TRANS" MODIFY ("SPLAN_TRANS_ID" NOT NULL ENABLE);
  ALTER TABLE "JFAS"."SPLAN_TRANS" ADD CONSTRAINT "SPLAN_TRANS_PK" PRIMARY KEY ("SPLAN_TRANS_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SPLAN_TRANS
--------------------------------------------------------

  ALTER TABLE "JFAS"."SPLAN_TRANS" ADD CONSTRAINT "SPLAN_TRANS_FK1" FOREIGN KEY ("TRANS_TYPE_CODE")
	  REFERENCES "JFAS"."LU_CODE" ("CODE") ENABLE;
  ALTER TABLE "JFAS"."SPLAN_TRANS" ADD CONSTRAINT "SPLAN_TRANS_FK2" FOREIGN KEY ("TRANS_STATUS_CODE")
	  REFERENCES "JFAS"."LU_CODE" ("CODE") ENABLE;
