-- create table BUDGET_NCFMS_LOAD
--DROP TABLE JFAS.BUDGET_NCFMS_LOAD CASCADE CONSTRAINTS;

CREATE TABLE JFAS.BUDGET_NCFMS_LOAD
(
  AGENCY_CODE       VARCHAR2(5 BYTE),
  FUND_CODE         VARCHAR2(20 BYTE),
  BUDGET_YEAR       VARCHAR2(4 BYTE),
  PROGRAM_CODE      VARCHAR2(20 BYTE),
  ACTIVITY          VARCHAR2(8 BYTE),
  STRAT_GOAL        VARCHAR2(8 BYTE),
  FUNDING_ORG       VARCHAR2(6 BYTE),
  MANAGING_UNIT     VARCHAR2(7 BYTE),
  APPROPRIATION_AMOUNT  NUMBER,
  PERM_TEMP_REDUCTIONS  NUMBER,
  AUTH_TEMP_UNAVAILABLE  NUMBER,
  TRANSFERS_IN_OUT  NUMBER,
  ANTICIPATED_COLLECTIONS  NUMBER,
  TOTAL_BUDGET_AUTHORITY  NUMBER,
  PY_CARRYFORWARD_AMOUNT  NUMBER,
  CY_APPROPRIATION_ORIG_AMOUNT  NUMBER,
  CY_APPROPRIATION_BALANCE  NUMBER,
  APPROPRIATION_BALANCE_TB  NUMBER,
  CY_APPORTIONMENT_ORIG_AMOUNT  NUMBER,
  CY_APPORTIONMENT_BALANCE  NUMBER,
  APPORTIONMENT_BALANCE_TB  NUMBER,
  CY_ALLOTMENT_ORIG_AMOUNT  NUMBER,
  CY_ALLOTMENT_BALANCE  NUMBER,
  ALLOTMENT_BALANCE_TB  NUMBER,
  CY_SUBALLOTMENT_ORIG_AMOUNT  NUMBER,
  CY_SUBALLOTMENT_BALANCE  NUMBER,
  SUBALLOTMENT_BALANCE_TB  NUMBER,
  CY_ALLOCATION_ORIG_AMOUNT  NUMBER,
  COMMITMENT_AMOUNT  NUMBER,
  OBLIGATION_AMOUNT  NUMBER,
  ALLOCATION_BALANCE_TB  NUMBER
);