
CREATE SEQUENCE  "JFAS"."SEQ_SPLAN_TRANS_DET"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1255 CACHE 20 NOORDER  NOCYCLE ;

--------------------------------------------------------
--  File created - Monday-April-13-2015   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table SPLAN_TRANS_DET
--------------------------------------------------------

  CREATE TABLE "JFAS"."SPLAN_TRANS_DET" 
   (	"SPLAN_TRANS_DET_ID" NUMBER, 
	"SPLAN_TRANS_ID" NUMBER, 
	"SPLAN_CAT_ID" NUMBER, 
	"AMOUNT" NUMBER, 
	"CREATE_DATE" DATE DEFAULT SYSDATE, 
	"UPDATE_DATE" DATE DEFAULT SYSDATE, 
	"CREATE_USER" VARCHAR2(20) DEFAULT 'mstein', 
	"UPDATE_USER" VARCHAR2(20) DEFAULT 'mstein'
   ) ;
--REM INSERTING into JFAS.SPLAN_TRANS_DET
--SET DEFINE OFF;

Insert into JFAS.SPLAN_TRANS_DET (SPLAN_TRANS_DET_ID,SPLAN_TRANS_ID,SPLAN_CAT_ID,AMOUNT,CREATE_DATE,UPDATE_DATE,CREATE_USER,UPDATE_USER) values (1209,1280,5,1013782250,to_date('13-APR-15','DD-MON-RR'),to_date('13-APR-15','DD-MON-RR'),'sas','sas');
Insert into JFAS.SPLAN_TRANS_DET (SPLAN_TRANS_DET_ID,SPLAN_TRANS_ID,SPLAN_CAT_ID,AMOUNT,CREATE_DATE,UPDATE_DATE,CREATE_USER,UPDATE_USER) values (1210,1281,7,7770638,to_date('13-APR-15','DD-MON-RR'),to_date('13-APR-15','DD-MON-RR'),'sas','sas');
Insert into JFAS.SPLAN_TRANS_DET (SPLAN_TRANS_DET_ID,SPLAN_TRANS_ID,SPLAN_CAT_ID,AMOUNT,CREATE_DATE,UPDATE_DATE,CREATE_USER,UPDATE_USER) values (1211,1282,8,0,to_date('13-APR-15','DD-MON-RR'),to_date('13-APR-15','DD-MON-RR'),'sas','sas');
Insert into JFAS.SPLAN_TRANS_DET (SPLAN_TRANS_DET_ID,SPLAN_TRANS_ID,SPLAN_CAT_ID,AMOUNT,CREATE_DATE,UPDATE_DATE,CREATE_USER,UPDATE_USER) values (1212,1283,9,4251688,to_date('13-APR-15','DD-MON-RR'),to_date('13-APR-15','DD-MON-RR'),'sas','sas');
Insert into JFAS.SPLAN_TRANS_DET (SPLAN_TRANS_DET_ID,SPLAN_TRANS_ID,SPLAN_CAT_ID,AMOUNT,CREATE_DATE,UPDATE_DATE,CREATE_USER,UPDATE_USER) values (1213,1284,10,48433683,to_date('13-APR-15','DD-MON-RR'),to_date('13-APR-15','DD-MON-RR'),'sas','sas');
Insert into JFAS.SPLAN_TRANS_DET (SPLAN_TRANS_DET_ID,SPLAN_TRANS_ID,SPLAN_CAT_ID,AMOUNT,CREATE_DATE,UPDATE_DATE,CREATE_USER,UPDATE_USER) values (1214,1285,11,49305963,to_date('13-APR-15','DD-MON-RR'),to_date('13-APR-15','DD-MON-RR'),'sas','sas');
Insert into JFAS.SPLAN_TRANS_DET (SPLAN_TRANS_DET_ID,SPLAN_TRANS_ID,SPLAN_CAT_ID,AMOUNT,CREATE_DATE,UPDATE_DATE,CREATE_USER,UPDATE_USER) values (1215,1286,12,21376961,to_date('13-APR-15','DD-MON-RR'),to_date('13-APR-15','DD-MON-RR'),'sas','sas');
Insert into JFAS.SPLAN_TRANS_DET (SPLAN_TRANS_DET_ID,SPLAN_TRANS_ID,SPLAN_CAT_ID,AMOUNT,CREATE_DATE,UPDATE_DATE,CREATE_USER,UPDATE_USER) values (1216,1287,13,0,to_date('13-APR-15','DD-MON-RR'),to_date('13-APR-15','DD-MON-RR'),'sas','sas');
Insert into JFAS.SPLAN_TRANS_DET (SPLAN_TRANS_DET_ID,SPLAN_TRANS_ID,SPLAN_CAT_ID,AMOUNT,CREATE_DATE,UPDATE_DATE,CREATE_USER,UPDATE_USER) values (1217,1288,15,161000000,to_date('13-APR-15','DD-MON-RR'),to_date('13-APR-15','DD-MON-RR'),'sas','sas');
Insert into JFAS.SPLAN_TRANS_DET (SPLAN_TRANS_DET_ID,SPLAN_TRANS_ID,SPLAN_CAT_ID,AMOUNT,CREATE_DATE,UPDATE_DATE,CREATE_USER,UPDATE_USER) values (1218,1289,21,8200000,to_date('13-APR-15','DD-MON-RR'),to_date('13-APR-15','DD-MON-RR'),'sas','sas');
Insert into JFAS.SPLAN_TRANS_DET (SPLAN_TRANS_DET_ID,SPLAN_TRANS_ID,SPLAN_CAT_ID,AMOUNT,CREATE_DATE,UPDATE_DATE,CREATE_USER,UPDATE_USER) values (1219,1290,22,68000000,to_date('13-APR-15','DD-MON-RR'),to_date('13-APR-15','DD-MON-RR'),'sas','sas');
Insert into JFAS.SPLAN_TRANS_DET (SPLAN_TRANS_DET_ID,SPLAN_TRANS_ID,SPLAN_CAT_ID,AMOUNT,CREATE_DATE,UPDATE_DATE,CREATE_USER,UPDATE_USER) values (1220,1291,23,0,to_date('13-APR-15','DD-MON-RR'),to_date('13-APR-15','DD-MON-RR'),'sas','sas');
Insert into JFAS.SPLAN_TRANS_DET (SPLAN_TRANS_DET_ID,SPLAN_TRANS_ID,SPLAN_CAT_ID,AMOUNT,CREATE_DATE,UPDATE_DATE,CREATE_USER,UPDATE_USER) values (1221,1292,24,702125,to_date('13-APR-15','DD-MON-RR'),to_date('13-APR-15','DD-MON-RR'),'sas','sas');
Insert into JFAS.SPLAN_TRANS_DET (SPLAN_TRANS_DET_ID,SPLAN_TRANS_ID,SPLAN_CAT_ID,AMOUNT,CREATE_DATE,UPDATE_DATE,CREATE_USER,UPDATE_USER) values (1222,1293,25,72263,to_date('13-APR-15','DD-MON-RR'),to_date('13-APR-15','DD-MON-RR'),'sas','sas');
Insert into JFAS.SPLAN_TRANS_DET (SPLAN_TRANS_DET_ID,SPLAN_TRANS_ID,SPLAN_CAT_ID,AMOUNT,CREATE_DATE,UPDATE_DATE,CREATE_USER,UPDATE_USER) values (1223,1294,26,10000000,to_date('13-APR-15','DD-MON-RR'),to_date('13-APR-15','DD-MON-RR'),'sas','sas');
Insert into JFAS.SPLAN_TRANS_DET (SPLAN_TRANS_DET_ID,SPLAN_TRANS_ID,SPLAN_CAT_ID,AMOUNT,CREATE_DATE,UPDATE_DATE,CREATE_USER,UPDATE_USER) values (1224,1295,27,1286375,to_date('13-APR-15','DD-MON-RR'),to_date('13-APR-15','DD-MON-RR'),'sas','sas');
Insert into JFAS.SPLAN_TRANS_DET (SPLAN_TRANS_DET_ID,SPLAN_TRANS_ID,SPLAN_CAT_ID,AMOUNT,CREATE_DATE,UPDATE_DATE,CREATE_USER,UPDATE_USER) values (1225,1296,28,491717,to_date('13-APR-15','DD-MON-RR'),to_date('13-APR-15','DD-MON-RR'),'sas','sas');
Insert into JFAS.SPLAN_TRANS_DET (SPLAN_TRANS_DET_ID,SPLAN_TRANS_ID,SPLAN_CAT_ID,AMOUNT,CREATE_DATE,UPDATE_DATE,CREATE_USER,UPDATE_USER) values (1226,1297,29,3280000,to_date('13-APR-15','DD-MON-RR'),to_date('13-APR-15','DD-MON-RR'),'sas','sas');
Insert into JFAS.SPLAN_TRANS_DET (SPLAN_TRANS_DET_ID,SPLAN_TRANS_ID,SPLAN_CAT_ID,AMOUNT,CREATE_DATE,UPDATE_DATE,CREATE_USER,UPDATE_USER) values (1227,1298,30,1906705,to_date('13-APR-15','DD-MON-RR'),to_date('13-APR-15','DD-MON-RR'),'sas','sas');
Insert into JFAS.SPLAN_TRANS_DET (SPLAN_TRANS_DET_ID,SPLAN_TRANS_ID,SPLAN_CAT_ID,AMOUNT,CREATE_DATE,UPDATE_DATE,CREATE_USER,UPDATE_USER) values (1228,1299,31,3556750,to_date('13-APR-15','DD-MON-RR'),to_date('13-APR-15','DD-MON-RR'),'sas','sas');
Insert into JFAS.SPLAN_TRANS_DET (SPLAN_TRANS_DET_ID,SPLAN_TRANS_ID,SPLAN_CAT_ID,AMOUNT,CREATE_DATE,UPDATE_DATE,CREATE_USER,UPDATE_USER) values (1229,1300,32,12710000,to_date('13-APR-15','DD-MON-RR'),to_date('13-APR-15','DD-MON-RR'),'sas','sas');
Insert into JFAS.SPLAN_TRANS_DET (SPLAN_TRANS_DET_ID,SPLAN_TRANS_ID,SPLAN_CAT_ID,AMOUNT,CREATE_DATE,UPDATE_DATE,CREATE_USER,UPDATE_USER) values (1230,1301,33,19035000,to_date('13-APR-15','DD-MON-RR'),to_date('13-APR-15','DD-MON-RR'),'sas','sas');
Insert into JFAS.SPLAN_TRANS_DET (SPLAN_TRANS_DET_ID,SPLAN_TRANS_ID,SPLAN_CAT_ID,AMOUNT,CREATE_DATE,UPDATE_DATE,CREATE_USER,UPDATE_USER) values (1231,1302,34,1121531,to_date('13-APR-15','DD-MON-RR'),to_date('13-APR-15','DD-MON-RR'),'sas','sas');
Insert into JFAS.SPLAN_TRANS_DET (SPLAN_TRANS_DET_ID,SPLAN_TRANS_ID,SPLAN_CAT_ID,AMOUNT,CREATE_DATE,UPDATE_DATE,CREATE_USER,UPDATE_USER) values (1232,1303,35,2050000,to_date('13-APR-15','DD-MON-RR'),to_date('13-APR-15','DD-MON-RR'),'sas','sas');
Insert into JFAS.SPLAN_TRANS_DET (SPLAN_TRANS_DET_ID,SPLAN_TRANS_ID,SPLAN_CAT_ID,AMOUNT,CREATE_DATE,UPDATE_DATE,CREATE_USER,UPDATE_USER) values (1233,1304,37,3633625,to_date('13-APR-15','DD-MON-RR'),to_date('13-APR-15','DD-MON-RR'),'sas','sas');
Insert into JFAS.SPLAN_TRANS_DET (SPLAN_TRANS_DET_ID,SPLAN_TRANS_ID,SPLAN_CAT_ID,AMOUNT,CREATE_DATE,UPDATE_DATE,CREATE_USER,UPDATE_USER) values (1234,1305,38,2000000,to_date('13-APR-15','DD-MON-RR'),to_date('13-APR-15','DD-MON-RR'),'sas','sas');
Insert into JFAS.SPLAN_TRANS_DET (SPLAN_TRANS_DET_ID,SPLAN_TRANS_ID,SPLAN_CAT_ID,AMOUNT,CREATE_DATE,UPDATE_DATE,CREATE_USER,UPDATE_USER) values (1235,1306,39,3000000,to_date('13-APR-15','DD-MON-RR'),to_date('13-APR-15','DD-MON-RR'),'sas','sas');
Insert into JFAS.SPLAN_TRANS_DET (SPLAN_TRANS_DET_ID,SPLAN_TRANS_ID,SPLAN_CAT_ID,AMOUNT,CREATE_DATE,UPDATE_DATE,CREATE_USER,UPDATE_USER) values (1236,1307,40,4588750,to_date('13-APR-15','DD-MON-RR'),to_date('13-APR-15','DD-MON-RR'),'sas','sas');
Insert into JFAS.SPLAN_TRANS_DET (SPLAN_TRANS_DET_ID,SPLAN_TRANS_ID,SPLAN_CAT_ID,AMOUNT,CREATE_DATE,UPDATE_DATE,CREATE_USER,UPDATE_USER) values (1237,1308,41,2091000,to_date('13-APR-15','DD-MON-RR'),to_date('13-APR-15','DD-MON-RR'),'sas','sas');
Insert into JFAS.SPLAN_TRANS_DET (SPLAN_TRANS_DET_ID,SPLAN_TRANS_ID,SPLAN_CAT_ID,AMOUNT,CREATE_DATE,UPDATE_DATE,CREATE_USER,UPDATE_USER) values (1238,1309,42,416150,to_date('13-APR-15','DD-MON-RR'),to_date('13-APR-15','DD-MON-RR'),'sas','sas');
Insert into JFAS.SPLAN_TRANS_DET (SPLAN_TRANS_DET_ID,SPLAN_TRANS_ID,SPLAN_CAT_ID,AMOUNT,CREATE_DATE,UPDATE_DATE,CREATE_USER,UPDATE_USER) values (1239,1310,43,5611452,to_date('13-APR-15','DD-MON-RR'),to_date('13-APR-15','DD-MON-RR'),'sas','sas');
Insert into JFAS.SPLAN_TRANS_DET (SPLAN_TRANS_DET_ID,SPLAN_TRANS_ID,SPLAN_CAT_ID,AMOUNT,CREATE_DATE,UPDATE_DATE,CREATE_USER,UPDATE_USER) values (1240,1311,45,83281075,to_date('13-APR-15','DD-MON-RR'),to_date('13-APR-15','DD-MON-RR'),'sas','sas');
Insert into JFAS.SPLAN_TRANS_DET (SPLAN_TRANS_DET_ID,SPLAN_TRANS_ID,SPLAN_CAT_ID,AMOUNT,CREATE_DATE,UPDATE_DATE,CREATE_USER,UPDATE_USER) values (1241,1312,400,13500000,to_date('13-APR-15','DD-MON-RR'),to_date('13-APR-15','DD-MON-RR'),'sas','sas');
Insert into JFAS.SPLAN_TRANS_DET (SPLAN_TRANS_DET_ID,SPLAN_TRANS_ID,SPLAN_CAT_ID,AMOUNT,CREATE_DATE,UPDATE_DATE,CREATE_USER,UPDATE_USER) values (1242,1313,401,1400000,to_date('13-APR-15','DD-MON-RR'),to_date('13-APR-15','DD-MON-RR'),'sas','sas');
Insert into JFAS.SPLAN_TRANS_DET (SPLAN_TRANS_DET_ID,SPLAN_TRANS_ID,SPLAN_CAT_ID,AMOUNT,CREATE_DATE,UPDATE_DATE,CREATE_USER,UPDATE_USER) values (1243,1314,402,100000,to_date('13-APR-15','DD-MON-RR'),to_date('13-APR-15','DD-MON-RR'),'sas','sas');
Insert into JFAS.SPLAN_TRANS_DET (SPLAN_TRANS_DET_ID,SPLAN_TRANS_ID,SPLAN_CAT_ID,AMOUNT,CREATE_DATE,UPDATE_DATE,CREATE_USER,UPDATE_USER) values (1244,1315,403,85000,to_date('13-APR-15','DD-MON-RR'),to_date('13-APR-15','DD-MON-RR'),'sas','sas');
Insert into JFAS.SPLAN_TRANS_DET (SPLAN_TRANS_DET_ID,SPLAN_TRANS_ID,SPLAN_CAT_ID,AMOUNT,CREATE_DATE,UPDATE_DATE,CREATE_USER,UPDATE_USER) values (1245,1316,404,400000,to_date('13-APR-15','DD-MON-RR'),to_date('13-APR-15','DD-MON-RR'),'sas','sas');
Insert into JFAS.SPLAN_TRANS_DET (SPLAN_TRANS_DET_ID,SPLAN_TRANS_ID,SPLAN_CAT_ID,AMOUNT,CREATE_DATE,UPDATE_DATE,CREATE_USER,UPDATE_USER) values (1246,1317,405,400000,to_date('13-APR-15','DD-MON-RR'),to_date('13-APR-15','DD-MON-RR'),'sas','sas');
Insert into JFAS.SPLAN_TRANS_DET (SPLAN_TRANS_DET_ID,SPLAN_TRANS_ID,SPLAN_CAT_ID,AMOUNT,CREATE_DATE,UPDATE_DATE,CREATE_USER,UPDATE_USER) values (1247,1318,406,650000,to_date('13-APR-15','DD-MON-RR'),to_date('13-APR-15','DD-MON-RR'),'sas','sas');
Insert into JFAS.SPLAN_TRANS_DET (SPLAN_TRANS_DET_ID,SPLAN_TRANS_ID,SPLAN_CAT_ID,AMOUNT,CREATE_DATE,UPDATE_DATE,CREATE_USER,UPDATE_USER) values (1248,1319,407,10000,to_date('13-APR-15','DD-MON-RR'),to_date('13-APR-15','DD-MON-RR'),'sas','sas');
Insert into JFAS.SPLAN_TRANS_DET (SPLAN_TRANS_DET_ID,SPLAN_TRANS_ID,SPLAN_CAT_ID,AMOUNT,CREATE_DATE,UPDATE_DATE,CREATE_USER,UPDATE_USER) values (1249,1320,408,800000,to_date('13-APR-15','DD-MON-RR'),to_date('13-APR-15','DD-MON-RR'),'sas','sas');
Insert into JFAS.SPLAN_TRANS_DET (SPLAN_TRANS_DET_ID,SPLAN_TRANS_ID,SPLAN_CAT_ID,AMOUNT,CREATE_DATE,UPDATE_DATE,CREATE_USER,UPDATE_USER) values (1250,1321,409,3925295,to_date('13-APR-15','DD-MON-RR'),to_date('13-APR-15','DD-MON-RR'),'sas','sas');
Insert into JFAS.SPLAN_TRANS_DET (SPLAN_TRANS_DET_ID,SPLAN_TRANS_ID,SPLAN_CAT_ID,AMOUNT,CREATE_DATE,UPDATE_DATE,CREATE_USER,UPDATE_USER) values (1251,1322,410,10000,to_date('13-APR-15','DD-MON-RR'),to_date('13-APR-15','DD-MON-RR'),'sas','sas');
Insert into JFAS.SPLAN_TRANS_DET (SPLAN_TRANS_DET_ID,SPLAN_TRANS_ID,SPLAN_CAT_ID,AMOUNT,CREATE_DATE,UPDATE_DATE,CREATE_USER,UPDATE_USER) values (1252,1323,46,7890040,to_date('13-APR-15','DD-MON-RR'),to_date('13-APR-15','DD-MON-RR'),'sas','sas');
Insert into JFAS.SPLAN_TRANS_DET (SPLAN_TRANS_DET_ID,SPLAN_TRANS_ID,SPLAN_CAT_ID,AMOUNT,CREATE_DATE,UPDATE_DATE,CREATE_USER,UPDATE_USER) values (1253,1324,379,5881964,to_date('13-APR-15','DD-MON-RR'),to_date('13-APR-15','DD-MON-RR'),'sas','sas');

--------------------------------------------------------
--  DDL for Index SPLAN_TRANS_DET_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "JFAS"."SPLAN_TRANS_DET_PK" ON "JFAS"."SPLAN_TRANS_DET" ("SPLAN_TRANS_DET_ID") 
  ;
--------------------------------------------------------
--  Constraints for Table SPLAN_TRANS_DET
--------------------------------------------------------

  ALTER TABLE "JFAS"."SPLAN_TRANS_DET" MODIFY ("UPDATE_DATE" NOT NULL ENABLE);
  ALTER TABLE "JFAS"."SPLAN_TRANS_DET" MODIFY ("UPDATE_USER" NOT NULL ENABLE);
  ALTER TABLE "JFAS"."SPLAN_TRANS_DET" MODIFY ("CREATE_DATE" NOT NULL ENABLE);
  ALTER TABLE "JFAS"."SPLAN_TRANS_DET" MODIFY ("CREATE_USER" NOT NULL ENABLE);
  ALTER TABLE "JFAS"."SPLAN_TRANS_DET" MODIFY ("AMOUNT" NOT NULL ENABLE);
  ALTER TABLE "JFAS"."SPLAN_TRANS_DET" MODIFY ("SPLAN_CAT_ID" NOT NULL ENABLE);
  ALTER TABLE "JFAS"."SPLAN_TRANS_DET" MODIFY ("SPLAN_TRANS_ID" NOT NULL ENABLE);
  ALTER TABLE "JFAS"."SPLAN_TRANS_DET" MODIFY ("SPLAN_TRANS_DET_ID" NOT NULL ENABLE);
  ALTER TABLE "JFAS"."SPLAN_TRANS_DET" ADD CONSTRAINT "SPLAN_TRANS_DET_PK" PRIMARY KEY ("SPLAN_TRANS_DET_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SPLAN_TRANS_DET
--------------------------------------------------------

  ALTER TABLE "JFAS"."SPLAN_TRANS_DET" ADD CONSTRAINT "SPLAN_TRANS_DET_FK1" FOREIGN KEY ("SPLAN_TRANS_ID")
	  REFERENCES "JFAS"."SPLAN_TRANS" ("SPLAN_TRANS_ID") ENABLE;
