LOAD DATA
truncate
INTO TABLE JFAS.EQUIPMENT_LOAD
FIELDS TERMINATED BY "," OPTIONALLY ENCLOSED BY '"'
trailing nullcols

(
name1 filler,
name2 filler, 
AAPP_NUM  INTEGER EXTERNAL,
AMOUNT  INTEGER EXTERNAL
)
